host: '127.0.0.1'
port: 0
http2: false
ssl:
  enabled: false
  cert: '/path/to/cert/file'
  key: '/path/to/key/file'
debug: true
dashboard:
  path: '/dashboard'
  logger:
    enabled: true
    type: 'combined'
router:
  logger:
      enabled: true
      type: 'combined'
  cors: true
  routes:
    GET /api/v1/account:
      bypass: false
      delay: 1000
      code: 200
      headers:
        Content-Type: 'application/json'
        Server: Nginx
      body: '{"name":"admin"}'