GET /api/v1/account:
  bypass: false
  delay: 1000
  code: 200
  headers:
    Content-Type: "application/json"
    Server: "Nginx"
  body: |-
    {
      "name": "admin"
    }
PUT /api/v1/account:
  bypass: false
  delay: 0
  code: 200
  headers:
    Content-Type: "application/json"
    Server: "Nginx"
ALL /api/v1/proxy/*:
  proxy:
    remote: 'https://jsonplaceholder.typicode.com'
    rewrite: ^/api/v1/proxy/(.*) /posts/$1
    headers:
      X-Real-IP: $remote_addr
      X-Forwarded-For: $proxy_add_x_forwarded_for
      X-Mockit-Proxy: 'true'
      Upgrade: $http_upgrade
      User-Agent: $http_user_agent
      Connection: 'upgrade'
      Host: $host
GET /api/v1/users/:id:
  code: 200
  body: |-
    {
      "id": 0,
      "name": "unknown"
    }
  cond:
    - case: params.id == 1
      body: |-
        {
          "id": 1,
          "name": "Alfonzo"
        }
    - case: params.id == 2
      body: |-
        {
          "id": 2
          "name": "Juanita"
        }
GET /api/v1/members/:id:
  code: 200
  body: |-
    {
      "id": ${params.id},
      "name": "${faker.internet.userName()}",
      "fullname": "${faker.name.firstName()} ${faker.name.lastName()}",
      "email": "${faker.internet.email()}",
    }
