GET /api/v1/account:
  bypass: false
  delay: 1000
  code: 200
  headers:
    Content-Type: "application/json"
    Server: "Nginx"
  body: |-
    {
      "name": "admin"
    }
PUT /api/v1/account:
  bypass: false
  delay: 0
  code: 200
  headers:
    Content-Type: "application/json"
    Server: "Nginx"
ALL /api/v1/proxy/*:
  proxy:
    remote: 'https://jsonplaceholder.typicode.com'
    rewrite: ^/api/v1/proxy/(.*) /posts/$1
    headers:
      X-Real-IP: $remote_addr
      X-Forwarded-For: $proxy_add_x_forwarded_for
      X-Mockit-Proxy: 'true'
      Upgrade: $http_upgrade
      User-Agent: $http_user_agent
      Connection: 'upgrade'
      Host: $host
GET /api/v1/users/:id:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "id": 0,
      "name": "unknown"
    }
  cond:
  - case: params.id == 1
    body: |-
      {
        "id": 1,
        "name": "Alfonzo"
      }
  - case: params.id == 2
    body: |-
      {
        "id": 2,
        "name": "Juanita"
      }
GET /api/v1/members/:id:
  code: 200
  headers:
    Content-Type: "application/json"
  body: |-
    {
      "index": ${params.id},
      "uid": ${faker.random.number() + params.id},
      "name": "${faker.internet.userName()}",
      "fullname": "${faker('zh_CN').name.firstName}${faker('zh_CN').name.lastName()}",
      "email": "${faker.internet.email}",
      "location": {
        "latitude": ${faker.address.latitude},
        "longitude": ${faker.address.longitude}
      },
      "desc": "${faker.lorem.paragraph}",
      "escape": "${'\{' + 'using curly braces inside interpo template' + '\}'}"
    }
